{
  "formatVersion": "1.1",
  "component": {
    "group": "com.csplib.pathbuilder",
    "module": "pathbuilder",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pathbuilder-1.0.0.jar",
          "url": "pathbuilder-1.0.0.jar",
          "size": 27349,
          "sha512": "38ef94d3f872e2914bc3cf22141a25a9fa45e67c48208cbef2997ba0b5ebde13094a23cea0c678e6685d8303b2f269404766042175efd3fff68b592dcda073b6",
          "sha256": "1e214da616c5af215e855c97e7410237504eca51684cd11729b98d50d7847a7b",
          "sha1": "fb1372a47c6b8c66674884b3c859d08e6447f3bd",
          "md5": "7f9fd3e224c4d2d3eba512598f1e29d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "pathbuilder-1.0.0.jar",
          "url": "pathbuilder-1.0.0.jar",
          "size": 27349,
          "sha512": "38ef94d3f872e2914bc3cf22141a25a9fa45e67c48208cbef2997ba0b5ebde13094a23cea0c678e6685d8303b2f269404766042175efd3fff68b592dcda073b6",
          "sha256": "1e214da616c5af215e855c97e7410237504eca51684cd11729b98d50d7847a7b",
          "sha1": "fb1372a47c6b8c66674884b3c859d08e6447f3bd",
          "md5": "7f9fd3e224c4d2d3eba512598f1e29d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pathbuilder-1.0.0-sources.jar",
          "url": "pathbuilder-1.0.0-sources.jar",
          "size": 12258,
          "sha512": "da7e8f5c11b0b1b7d6fc046465936a65cd20d312977d6dd0f0ce40a7c0af6ebd06af6dd0cf61dc69276bcb82af096b5165359693ba56a12217412b816598b9b1",
          "sha256": "6d0be3b7fd10d494cbe725d48622a3d2ef8b83b395ad1eeec7a077c8fba0f541",
          "sha1": "3a684e415a06938b876255e784fc0b331c8388eb",
          "md5": "69b7274a3b2d3f51af6d5f9f559f61f1"
        }
      ]
    }
  ]
}
