{
  "formatVersion": "1.1",
  "component": {
    "group": "com.csplib.pathbuilder",
    "module": "pathbuilder",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pathbuilder-2.2.1.jar",
          "url": "pathbuilder-2.2.1.jar",
          "size": 65107,
          "sha512": "0be415c603d9933dec03c76c3f4759f088f929d3bd618cda619b74e7a1bc826887be9046de3e39816e445a4877d7e41b52505fffe149c38d9ccfaf952502e414",
          "sha256": "1a50cc2970e688b2083897f1ef1517d7dd4f44f907ebabb6f0f3e7fe795bb57a",
          "sha1": "115634fef78ad3efa02e488f738940c72e16cf8a",
          "md5": "7ec3fb85ab127b77a899d8f63bf6364b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "com.github.therekrab",
          "module": "autopilot",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "pathbuilder-2.2.1.jar",
          "url": "pathbuilder-2.2.1.jar",
          "size": 65107,
          "sha512": "0be415c603d9933dec03c76c3f4759f088f929d3bd618cda619b74e7a1bc826887be9046de3e39816e445a4877d7e41b52505fffe149c38d9ccfaf952502e414",
          "sha256": "1a50cc2970e688b2083897f1ef1517d7dd4f44f907ebabb6f0f3e7fe795bb57a",
          "sha1": "115634fef78ad3efa02e488f738940c72e16cf8a",
          "md5": "7ec3fb85ab127b77a899d8f63bf6364b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pathbuilder-2.2.1-sources.jar",
          "url": "pathbuilder-2.2.1-sources.jar",
          "size": 25494,
          "sha512": "3cb2a15f6eac728be9103c5b94c3eb09e8b686b7faf10ca58a6d53ce0a14e03a87ecb894f3acf547f9fa84c567bd3b665a2afda5ed3936d82d0cfa92d01c64b8",
          "sha256": "025f7bc7038efce3e69728458786720ceb1e5bd22d120039cb6af5b90944f1ef",
          "sha1": "85f369e15069b368f5c48c9aa76f4833493b93bd",
          "md5": "112ffb3b685f89b140eb63513d9ceb94"
        }
      ]
    }
  ]
}
