{
  "formatVersion": "1.1",
  "component": {
    "group": "com.csplib.pathbuilder",
    "module": "pathbuilder",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pathbuilder-2.1.0.jar",
          "url": "pathbuilder-2.1.0.jar",
          "size": 62722,
          "sha512": "c706a1cb1b526d9b5649ba3564a35a35e0941d412d295a5d8f181d71a4788a588d7b4241446bd56f8951cceca4ea07ee971d7c0f593b60c65a225d1b7e195793",
          "sha256": "a550cdc8dfdf8a52747cbe78700d0727c95fed70d94fc3e4147649ddcc4bf8e2",
          "sha1": "6b292850ae9c224536cbf8916764167dc11c5d59",
          "md5": "19ac513e1d658e49773826c25b2e9b2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "com.github.therekrab",
          "module": "autopilot",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "pathbuilder-2.1.0.jar",
          "url": "pathbuilder-2.1.0.jar",
          "size": 62722,
          "sha512": "c706a1cb1b526d9b5649ba3564a35a35e0941d412d295a5d8f181d71a4788a588d7b4241446bd56f8951cceca4ea07ee971d7c0f593b60c65a225d1b7e195793",
          "sha256": "a550cdc8dfdf8a52747cbe78700d0727c95fed70d94fc3e4147649ddcc4bf8e2",
          "sha1": "6b292850ae9c224536cbf8916764167dc11c5d59",
          "md5": "19ac513e1d658e49773826c25b2e9b2d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pathbuilder-2.1.0-sources.jar",
          "url": "pathbuilder-2.1.0-sources.jar",
          "size": 25137,
          "sha512": "b5daea198de0dd193428f54fad6ff53df9433cfc000e923846338469b22d0eaf5f77efbb51e0a3570cf1e2d31e8cc6b031d127d03f736dbf54bd65b263ca8d3a",
          "sha256": "cac58b3113cee88b01b5f8de4e974b795478cc495dcd79b972b72319a61a023e",
          "sha1": "0208491067b2ee250894f764647d72bc195d4f60",
          "md5": "02bc103b3973c1ab513f124992364555"
        }
      ]
    }
  ]
}
